In [49]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [50]:
#importing dataset
data_set = pd.read_csv('Data1.csv')

In [51]:
data_set.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [52]:
X = data_set.iloc[:,:-1].values
Y = data_set.iloc[:,-1].values

In [53]:
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [54]:
#find the missing data(fill the missing values with mean value)
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [55]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
#encoding categorical data
LabelEncoder / OneHotEncoder

In [56]:
from sklearn.preprocessing import LabelEncoder
label_enc_x = LabelEncoder()
X[:,0] = label_enc_x.fit_transform(X[:,0])

In [57]:
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [58]:
#OneHOtEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [59]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [62]:
#ENcoding the Dependent
le = LabelEncoder()
Y = le.fit_transform(Y)

In [64]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


In [65]:
#splitting the dataset into training and testing

In [85]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.3,random_state=1)

In [90]:
print(X_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [87]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]


In [91]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.fit_transform(X_test[:,3:])

In [93]:
print(X_train)
print(X_test)

[[0.0 1.0 0.0 -0.038910211282047996 -0.22960023388015188]
 [1.0 0.0 0.0 0.5058327466666259 0.49120534884662787]
 [0.0 0.0 1.0 -0.3112816902563849 -0.4731156334500103]
 [0.0 0.0 1.0 -1.809324824615238 -1.6127677034369463]
 [1.0 0.0 0.0 1.0505757046152997 1.1048641557626704]
 [0.0 1.0 0.0 1.3229471835896367 1.455526331143266]
 [1.0 0.0 0.0 -0.7198389087178904 -0.736112264985457]]
[[0.0 1.0 0.0 -1.3880272079128577 -0.5513801778287937]
 [1.0 0.0 0.0 0.4594174561401711 1.40351317992784]
 [0.0 0.0 1.0 0.9286097517726866 -0.8521330020990451]]
