<a href="https://colab.research.google.com/github/masnaashraf/Python-and-ML/blob/main/logistic_regression_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#employee performance dataset
#Dependend variable-attrition

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
from sklearn.ensemble import RandomForestRegressor
rfr= RandomForestRegressor(random_state=42)

from sklearn.linear_model import LogisticRegression
log= LogisticRegression()
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier(random_state=42)

# simple imputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

#KNN Imputer
from sklearn.impute import KNNImputer

import warnings
warnings.filterwarnings("ignore")


In [ ]:
emppr=pd.read_csv("/content/Employee_Performance.csv")
emppr.head()


EmpNumber  Age Gender EducationBackground MaritalStatus    EmpDepartment  \
0  E1001000   32   Male           Marketing        Single            Sales   
1  E1001006   47   Male           Marketing        Single            Sales   
2  E1001007   40   Male       Life Sciences       Married            Sales   
3  E1001009   41   Male     Human Resources      Divorced  Human Resources   
4  E1001010   60   Male           Marketing        Single            Sales   

        EmpJobRole BusinessTravelFrequency  DistanceFromHome  \
0  Sales Executive           Travel_Rarely                10   
1  Sales Executive           Travel_Rarely                14   
2  Sales Executive       Travel_Frequently                 5   
3          Manager           Travel_Rarely                10   
4  Sales Executive           Travel_Rarely                16   

   EmpEducationLevel  ...  EmpRelationshipSatisfaction  \
0                  3  ...                            4   
1                  4  ...                            4   
2                  4  ...                            3   
3                  4  ...                            2   
4                  4  ...                            4   

   TotalWorkExperienceInYears  TrainingTimesLastYear  EmpWorkLifeBalance  \
0                          10                      2                   2   
1                          20                      2                   3   
2                          20                      2                   3   
3                          23                      2                   2   
4                          10                      1                   3   

   ExperienceYearsAtThisCompany  ExperienceYearsInCurrentRole  \
0                            10                             7   
1                             7                             7   
2                            18                            13   
3                            21                             6   
4                             2                             2   

  YearsSinceLastPromotion  YearsWithCurrManager  Attrition  PerformanceRating  
0                       0                     8         No                  3  
1                       1                     7         No                  3  
2                       1                    12         No                  4  
3                      12                     6         No                  3  
4                       2                     2         No                  3  

[5 rows x 28 columns]

In [ ]:
crt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype 
---  ------                        --------------  ----- 
 0   EmpNumber                     1200 non-null   object
 1   Age                           1200 non-null   int64 
 2   Gender                        1200 non-null   object
 3   EducationBackground           1200 non-null   object
 4   MaritalStatus                 1200 non-null   object
 5   EmpDepartment                 1200 non-null   object
 6   EmpJobRole                    1200 non-null   object
 7   BusinessTravelFrequency       1200 non-null   object
 8   DistanceFromHome              1200 non-null   int64 
 9   EmpEducationLevel             1200 non-null   int64 
 10  EmpEnvironmentSatisfaction    1200 non-null   int64 
 11  EmpHourlyRate                 1200 non-null   int64 
 12  EmpJobInvolvement             1200 non-null   int64 
 13  EmpJobLevel       

In [ ]:
emppr.isna().sum()

EmpNumber                       0
Age                             0
Gender                          0
EducationBackground             0
MaritalStatus                   0
EmpDepartment                   0
EmpJobRole                      0
BusinessTravelFrequency         0
DistanceFromHome                0
EmpEducationLevel               0
EmpEnvironmentSatisfaction      0
EmpHourlyRate                   0
EmpJobInvolvement               0
EmpJobLevel                     0
EmpJobSatisfaction              0
NumCompaniesWorked              0
OverTime                        0
EmpLastSalaryHikePercent        0
EmpRelationshipSatisfaction     0
TotalWorkExperienceInYears      0
TrainingTimesLastYear           0
EmpWorkLifeBalance              0
ExperienceYearsAtThisCompany    0
ExperienceYearsInCurrentRole    0
YearsSinceLastPromotion         0
YearsWithCurrManager            0
Attrition                       0
PerformanceRating               0
dtype: int64

In [ ]:
emppr=emppr.drop("EmpNumber",axis=1)

In [ ]:
emppr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 27 columns):
 #   Column                        Non-Null Count  Dtype 
---  ------                        --------------  ----- 
 0   Age                           1200 non-null   int64 
 1   Gender                        1200 non-null   object
 2   EducationBackground           1200 non-null   object
 3   MaritalStatus                 1200 non-null   object
 4   EmpDepartment                 1200 non-null   object
 5   EmpJobRole                    1200 non-null   object
 6   BusinessTravelFrequency       1200 non-null   object
 7   DistanceFromHome              1200 non-null   int64 
 8   EmpEducationLevel             1200 non-null   int64 
 9   EmpEnvironmentSatisfaction    1200 non-null   int64 
 10  EmpHourlyRate                 1200 non-null   int64 
 11  EmpJobInvolvement             1200 non-null   int64 
 12  EmpJobLevel                   1200 non-null   int64 
 13  EmpJobSatisfaction

In [ ]:
emppr["Attrition"].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
x = emppr.iloc[:,:-2].values
y = emppr.iloc[:,-2].values

In [ ]:
z=y = emppr.iloc[:,-1].values

In [ ]:
x_new=[x,z]

In [ ]:
x_new

[array([[32, 'Male', 'Marketing', ..., 7, 0, 8],
        [47, 'Male', 'Marketing', ..., 7, 1, 7],
        [40, 'Male', 'Life Sciences', ..., 13, 1, 12],
        ...,
        [50, 'Male', 'Medical', ..., 8, 3, 8],
        [34, 'Female', 'Medical', ..., 7, 7, 7],
        [24, 'Female', 'Life Sciences', ..., 2, 2, 0]], dtype=object),
 array([3, 3, 4, ..., 3, 3, 2])]

In [ ]:
#encoding categorical data

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1,2,3,4,5,6,15])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 0.0 ... 7 0 8]
 [0.0 1.0 0.0 ... 7 1 7]
 [0.0 1.0 0.0 ... 13 1 12]
 ...
 [0.0 1.0 0.0 ... 8 3 8]
 [1.0 0.0 0.0 ... 7 7 7]
 [1.0 0.0 0.0 ... 2 2 0]]


In [ ]:
y=pd.DataFrame(y)

In [ ]:
from sklearn.preprocessing import LabelEncoder
dep=LabelEncoder()
y=dep.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state=2)

In [ ]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test = st.fit_transform(x_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rdf = RandomForestClassifier(n_estimators=100,random_state =0)

In [ ]:
print(rdf)

RandomForestClassifier(random_state=0)


In [ ]:
rdf.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [ ]:
y_train_pred = rdf.predict(x_train)
y_test_pred = rdf.predict(x_test)

In [ ]:
rdf.score(x_train,y_train)

1.0

In [ ]:
rdf.score(x_test,y_test)

0.875

In [ ]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(rdf,x,y,cv=5)
scores

array([0.875     , 0.91666667, 0.93333333, 0.87916667, 0.87083333])

In [ ]:
#fit the model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 2)
classifier.fit(x_train,y_train)


LogisticRegression(random_state=2)

In [ ]:
y_pred_train = classifier.predict(x_train)

In [ ]:
y_pred_test = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_test)
cm

array([[ 34,  20,   2],
       [ 17, 234,   9],
       [  2,  23,  19]])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.64      0.61      0.62        56
           1       0.84      0.90      0.87       260
           2       0.63      0.43      0.51        44

    accuracy                           0.80       360
   macro avg       0.71      0.65      0.67       360
weighted avg       0.79      0.80      0.79       360

