In [1]:
#more than one predictor variable(multiple regression)

In [3]:
#assumption
#linear relation between target and predictor varibale
#the regression residuals normally distributed
#no multicollinearity or little between coorealtion independent varibale

In [6]:
#data pre processing steps
#fit our model to training dataset
#predict the result

In [8]:
#import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [32]:
#immporting dataset
data_set = pd.read_csv('50_Startups.csv')

In [12]:
data_set.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [33]:
#extraxt our dependent and independent varibales
x = data_set.iloc[:,:-1].values
y = data_set.iloc[:,-1].values

In [34]:
print(x)
#print(y)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [36]:
#encoding categorial data(dummy variables)
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[3])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [49]:
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [39]:
#split ourdataset into training and testing

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=3)

In [41]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(35, 6)
(35,)
(15, 6)
(15,)


In [42]:
#train our MLR model on training dataset
from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(x_train,y_train)

In [43]:
print(model)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)


In [45]:
#predicting our test set results
y_pred = model.predict(x_test)

In [46]:
print(y_test," ",y_pred)

[141585.52  81005.76 149759.96  42559.73  97483.56 103282.38 134307.35
  35673.41  64926.08 156122.51  90708.19 108733.99  89949.14 124266.9
 166187.94]   [127494.8466821   88057.98277738 159817.78591602  44493.11534693
  94177.97036162  93517.78201889 128102.73948284  54597.1587387
  44825.03664632 161243.40424548  70396.62791491 108677.56354726
  97645.27752446 128255.64710487 176143.64093246]


In [47]:
x_pred = model.predict(x_train)

In [48]:
print("train score", model.score(x_train,y_train))
print("test score", model.score(x_test,y_test))

train score 0.9537312094009914
test score 0.9160451837871486
