<a href="https://colab.research.google.com/github/masnaashraf/Python-and-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1=[i for i in range(0,100)]
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [ ]:
import sys
b=10
print(sys.getsizeof(b))
print(sys.getsizeof(b) * len(list1))

28
2800


In [ ]:
import numpy as np
np_arr=np.arange(0,100)
print(np_arr)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
#item size of single element in the array
print(np_arr.itemsize)

8


In [ ]:
#size of complete lements in the np array
print(np_arr.itemsize*np_arr.size)

800


from above two example computation memeory taken by storing numbers 0 to 100 in list is 2800 and the memory used to store same elements using numpy is 800.
that is why we can say that numpy is mopre powerfull than list

broadcasting in Numpy-

In [ ]:
a=[1,2,3,4,5]
b=np.array([1,2,3,4,5])
print(f"a is {type(a)},b is {type(b)}")

a is <class 'list'>,b is <class 'numpy.ndarray'>


In [ ]:
k=np.array(a)
k

array([1, 2, 3, 4, 5])

type conversion not possible from higher data type to lower data type

In [ ]:
a=[1,2,3,"4",5]
l=np.array(a)   #array is converted to the higher order datatype
print(l)

['1' '2' '3' '4' '5']


In [ ]:
f=np.array(a,dtype=int)
print(f)

[1 2 3 4 5]


In [ ]:
a=['1','2','3','4','5']
h=np.array(a*3)
print(h)

['1' '2' '3' '4' '5' '1' '2' '3' '4' '5' '1' '2' '3' '4' '5']


In [ ]:
import numpy as np
a=['1','2','3','4','5']
h=np.array(a , dtype=int)
ans=h*3
ans

#when we try to execute the multiplication to a numpy array after creating it

array([ 3,  6,  9, 12, 15])

In [ ]:
c=np.array([1,1,1])
print(c)

[1 1 1]


In [ ]:
#creating
c=np.ones(3,dtype=int)
c

array([1, 1, 1])

In [ ]:
#shape array
c.shape 
#1 D array

(3,)

In [ ]:
d=np.ones((3,3),dtype=int)
d

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
d.shape

(3, 3)

In [ ]:
f=np.ones(9,dtype=int)
f

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
print(f.reshape(3,3))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
e=np.zeros((3,3)) #dtype is float by default
e

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
e=np.zeros((3,3),dtype=int)
e

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
b=np.full((3,3),4)
b

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
b=np.full((3,3),4,dtype=float)
b

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [ ]:
#single dimenstional array with 3 elemnts
c=np.full((3,),4)
c

array([4, 4, 4])

In [ ]:
#printinting identity matrix of given dimension work only with square matrix like 2*2,#*3 etc.. not with 3*2
b=np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#printinting identity matrix of given dimension
b=np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [ ]:
#linspace
#print from 2 to 10 with regular/same intervels
b=np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [ ]:
#linspace
b=np.linspace(2,10)
b

In [ ]:
#creating random value [0,1) include 0 and excluding 1
b=np.random.rand(3) # prints 3 random numbers between 0 and 1
b

array([0.03332586, 0.73421088, 0.43638514])

In [ ]:
#each random number will be multiplied by 3
b=np.random.rand(3)*3
b

array([0.54658787, 0.60502136, 0.40704964])

In [ ]:
c=np.random.rand(4)
c

array([0.13085833, 0.39251952, 0.6762316 , 0.1632493 ])

In [ ]:
#random number in 3*2 matrix
f=np.random.rand(3,2)
f

array([[0.83714641, 0.68493839],
       [0.50153561, 0.01395511],
       [0.70199606, 0.67080607]])

In [ ]:
g=np.random.random(3)
g

array([0.84942822, 0.25147083, 0.35758937])

In [ ]:
g=np.random.random(3,2)#THIS DOESNT WORK WITH  multidimensional ARRAY
g

In [ ]:
#printing random integer number between 2,4 
h=np.random.randint(2,4)
h

3

In [ ]:
h=np.random.randint(2,7,10)
h

array([3, 2, 3, 3, 5, 2, 6, 4, 5, 2])

**indexing and slicing**

strides-bytes size required to store next value.(byte of data required to store next value)

a=[1,2,3,4,5]
if each value take 4 bytes to store then the value 2 require 8 bytes to store`


In [ ]:
import numpy as np

li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
print(arr.data) #gives the memory size
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int64
(8,)


In [ ]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [ ]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int64
(32, 8)


In [ ]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2, 1])

10
10
10


In [ ]:
print(li_2d[1][:3])
print(arr_2d[1, :3])

[5, 6, 7]
[5 6 7]


In [ ]:
print(li_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]


In [ ]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [ ]:
print(li_2d[0:3])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [ ]:
print(li_2d[0:3][0])

[1, 2, 3, 4]


In [ ]:
print(li_2d[0:3][1])

[5, 6, 7, 8]


In [ ]:
print(arr_2d[0:3, 2])

[ 3  7 11]


In [ ]:
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1:3])

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


In [ ]:
#to print element from each list
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1][0])

[[10 11]
 [14 15]]
13


In [ ]:
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1][1:3])

[[10 11]
 [14 15]]
[14, 15]


In [ ]:
print(arr_2d)
print(arr_2d[0:3,-3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 2  6 10]


In [ ]:
print(arr_2d[0:3:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
print(arr_2d[0:3,2])

[ 3  7 11]


In [ ]:
print(arr_2d[2][1])

10


In [ ]:
print(arr_2d[2,1])

10


In [ ]:
print(arr_2d[0:3,])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np 

a = np.arange(10) 
b = a[5] 
print(a)
b

[0 1 2 3 4 5 6 7 8 9]


5

In [ ]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:') 
print(a) 

# this returns array of items in the second column 
print('The items in the second column are:') 
print(a[...,1]) 
  

# Now we will slice all items from the second row 
print('The items in the second row are:')
print(a[1,...]) 
  

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:') 
print(a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
The items in the second column are:
[2 4 5]
The items in the second row are:
[3 4 5]
The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]


In [ ]:
np.diag(arr_2d)

array([ 1,  6, 11, 16])

In [ ]:
np.diag(arr_2d,1) #upper triangle diagonal

array([ 2,  7, 12])

In [ ]:
np.diag(arr_2d,-1) #lower triangle diagonal.

array([ 5, 10, 15])

In [ ]:
print(arr_2d.diagonal())

[ 1  6 11 16]


In [ ]:
#printing the diagonal element
print([arr_2d[i][i] for i in range(len(arr_2d))])

[1, 6, 11, 16]


In [ ]:
for i in range(len(arr_2d)):
  print(i)

0
1
2
3


In [ ]:
for i in range(len(arr_2d)):
  print(arr_2d[i])

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [ ]:
for i in range(len(arr_2d)):
  print(arr_2d[i][0])

1
5
9
13


In [ ]:
for i in range(len(arr_2d)):
  print(arr_2d[0][i])

1
2
3
4


In [ ]:
for i in range(len(arr_2d)):
  for j in range(i):
    print(arr_2d[i][j])

5
9
10
13
14
15


In [ ]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#printing diagnonal element in reverse order
print([arr_2d[i][len(arr_2d)-i-1] for i in range(len(arr_2d))])

[4, 7, 10, 13]


4-0-1=3-[0][3]=4
4-1-1=2-[1][2]=7
4-2-1=1[2][1]=10
4-3-1=0-[3][0]=13


print([arr[i][i] for i in range(len(arr)-1,-1,-1)])


In [ ]:
#printing diagonal from downwards
print([arr_2d[i][i] for i in range(len(arr_2d)-1,-1,-1)]) #start,end,step
len(arr_2d)

[16, 11, 6, 1]


4

4-1 =(3,-1,-1)
[3][3]=16
[2][2]=11
[1][1]=6
[0][0]=1

In [ ]:

for i in range(len(arr_2d)):
  print(arr_2d[i][len(arr_2d)-1-i])

4
7
10
13


4-1-0=3
[0][3]
[1][4-1-1]=[1][2]
[2][4-2-1]=[2][1]
[3][4-3-1]=[3][0]

In [ ]:
from numpy import random
b=random.binomial(n=10,p=0.5,size=10)
b

array([5, 5, 6, 4, 5, 5, 5, 4, 4, 5])

In [ ]:
from numpy import random
b=random.normal(n=10,p=0.5,size=10)
b

In [ ]:
f=np.arange(9,50) #creating an array in the range of 9 to 50 excluding 50

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [ ]:
f=np.linspace(9,49,dtype=int)

f

array([ 9,  9, 10, 11, 12, 13, 13, 14, 15, 16, 17, 17, 18, 19, 20, 21, 22,
       22, 23, 24, 25, 26, 26, 27, 28, 29, 30, 31, 31, 32, 33, 34, 35, 35,
       36, 37, 38, 39, 40, 40, 41, 42, 43, 44, 44, 45, 46, 47, 48, 49])

In [ ]:
f=np.linspace(9,49,dtype=int)

for i in f:
  print(i,end=" ")

9 9 10 11 12 13 13 14 15 16 17 17 18 19 20 21 22 22 23 24 25 26 26 27 28 29 30 31 31 32 33 34 35 35 36 37 38 39 40 40 41 42 43 44 44 45 46 47 48 49 

In [ ]:
#create
t=np.eye(5,6,dtype=int)
t

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

**boolean**

In [ ]:
a=[1,2,3,4,5,6,7,8]
print(a[1]>5)

False


In [ ]:
a=[1,2,3,4,5,6,7,8]
print(a[a[5]>5])

2


passing boolean array to original array so this will only print the array with true values alone

In [ ]:
a=np.array(["t","r","e","f","g","h","i","j"])
b=np.random.randint(1,20,8)
print(a)
print(b)

['t' 'r' 'e' 'f' 'g' 'h' 'i' 'j']
[ 2 14 13 11 14 15  3 15]


In [ ]:
print(b>5) #creates a boolean array where value > 5 is set to true other wise fasle

[False  True  True  True  True  True False  True]


In [ ]:
bool_arr=b>10
print(bool_arr)
newarr=b[bool_arr]  #prints only values from b for which bool_arr value is true
print(newarr)

[False  True  True  True  True  True False  True]
[14 13 11 14 15 15]


In [ ]:
bool_str=b<10
print(bool_str)
newstr=a[bool_str]
print(newstr)

[ True False False False False False  True False]
['t' 'i']


In [ ]:
n_arr=b[b>12]
print(n_arr)

[14 13 14 15 15]


In [ ]:
n_arr=b[(b>10) & (b<18)]
print(n_arr)

[14 13 11 14 15 15]


In [ ]:
n_arr=b[b==13]
print(n_arr)

[13]


In [ ]:
n=b[b==100]
print(n)   #if element is not present it gives an empty list

[]


In [ ]:
str_arr=a[a =='t']
print(str_arr)

['t']


In [ ]:
str_b=a=='t'
print(str_b)
n=b[str_b]
print(n)

[ True False False False False False False False]
[2]


In [ ]:
str_arr= a[(a == 't') | ( a== 'r')]
print(str_arr)

['t' 'r']


where function used to find the index

In [ ]:
ind=np.where(b==10)  #when element is not present answer is an empty array
print(ind)

(array([], dtype=int64),)


In [ ]:
ind=np.where(b==13)
print(ind)

(array([2]),)


In [ ]:
print(b[ind]) 

[13]


In [ ]:
ind=np.where(b>10) #give the index of element whose value is greater than 10
print(ind)
print(b[ind])      #pint element corresponding to each index

(array([1, 2, 3, 4, 5, 7]),)
[14 13 11 14 15 15]


In [ ]:
import numpy as np
c=np.random.randint(1,30,(5,6)) #creating 5*6 array using randint and numpy
c

array([[12, 13, 28, 29,  2, 16],
       [ 6, 22,  3,  2,  2,  9],
       [ 5, 20, 10, 14,  9, 24],
       [24, 10, 12, 27, 18, 17],
       [29, 24, 25, 25, 19, 20]])

In [ ]:
b=c[c>20]
print(b)
f=c>20
print(f)



[29 21 27 28 25 26 24 21 23 21 28]
[[ True False  True False False False]
 [False  True False  True False False]
 [False  True False False False False]
 [False False  True  True  True False]
 [ True  True  True False False False]]


In [ ]:
c=np.random.randint(1,30,(5,6))
print(c)
ind=np.where(c>20)
print(c[ind])

[[29  9 21  8  8  1]
 [ 8 27  6 28 20 18]
 [ 1 25  4 18 16  8]
 [ 2  7 26 24 21  9]
 [23 21 28  5 11 19]]
[29 21 27 28 25 26 24 21 23 21 28]


In [ ]:
v=c[:,3]==28 # checking from all rows 3rdcolunm
v

array([False,  True, False, False, False])

In [ ]:
v=c[:,3]==28 # checking from all rows 3rdcolunm
v

In [ ]:
v=c[:,:]==28 # checking from all rows and column for value 28
v

array([[False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False]])

mathematical function in numpy

In [ ]:
a=np.arange(1,6)
b=np.arange(1,6)
print(a)
print(b)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [ ]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())
print(a.argmin()) #index position of elemnt with max value
print(a.argmax()) #index position of elemnt with min value

15
3.0
1
5
0
4


In [ ]:
print(a==b)

[ True  True  True  True  True]


In [ ]:
print(a==b)
print(a>b)
print(a<b)
print(a<=b)

[ True  True  True  True  True]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]


argmin-index of minimum value
argmax-index of maxmum value
broadcasting-copyimg vaLUE
for broadcasting any one of the dimension from two arrays should be same

In [ ]:
arr=np.arange(1,7)
print(arr)
arr[3:]=100
print(arr)

[1 2 3 4 5 6]
[  1   2   3 100 100 100]


In [ ]:
arr1=np.arange(0,7)
arr1[3:]=500
print(arr1)

[  0   1   2 500 500 500 500]


In [ ]:
arr2=arr.copy()
print(arr2)

[  1   2   3 100 100 100]


**Broadcasting**

broadcasting-copyimg vaLUE for broadcasting any one of the dimension from two arrays should be same

In [ ]:
x=np.random.randint(1,10,(3,3))
y=np.random.randint(1,10,(3,1))
print(x,"\n",y)
print(x-y)

[[6 2 4]
 [4 2 2]
 [8 1 7]] 
 [[4]
 [3]
 [9]]
[[ 2 -2  0]
 [ 1 -1 -1]
 [-1 -8 -2]]


In [ ]:
x=np.random.randint(1,10,(3,2))
y=np.random.randint(1,10,(2,1))
print(x,"\n",y) #ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 
#here corresponding dimensions of two array is not same and broadcasting is not possible
print(x-y)

given an integer array of size 10
print the index of elementswhich are multiple of 3
note generate the following arrray
array [1,3,5,7,9,11,13,15,17,19]

In [ ]:
arr1=np.array([1,3,5,7,9,11,13,15,17,19])
list1=[]
for i in range(len(arr1)):
  if arr1[i]%3==0:
    list1.append(i)
print(list1)

[1, 4, 7]


In [ ]:
nparray=np.arange(1,20,2)
for i in np.where(nparray%3==0):
  print(i,end=" ")


[1 4 7] 

In [ ]:
nparray=np.arange(1,20,2)
for i in np.where(nparray%3==0)[0]:
  print(i,end=" ")


1 4 7 

In [ ]:
arr2=np.arange(1,11,1)
arr2[arr2%2!=0]=-1
arr2

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [ ]:
arr2=np.arange(1,11,1)
arrnew=arr2%2!=0
arr2[arrnew]=-1
arr2


array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

given an integer array of size 9 and replace the first occurances of max value by 0

In [ ]:
arr3=np.array([11,2,13,4,15,6,27,8,19])

a=arr3.argmax()

for i in range(len(arr3)):
  if i==a:
    arr3[i]=0
print(arr3)


[11  2 13  4 15  6  0  8 19]


In [ ]:
arr3=np.array([1,2,13,4,15,6,27,8,19])
index=arr3.argmax()
arr3[index]=0
print(arr3)


[ 1  2 13  4 15  6  0  8 19]


In [ ]:
arr3=np.array([1,2,13,4,15,6,27,8,19])
index=arr3.argmax()
arr3[index]=0
print(arr3)


[ 1  2 13  4 15  6  0  8 19]


In [ ]:
arr3=np.array([1,2,13,4,15,6,27,8,19])
index=arr3.argmax()
arr3[index]=0
for i in arr3:
  print(i,end=" ")


1 2 13 4 15 6 0 8 19 

In [ ]:
import numpy as np
arr3=np.array([1,2,13,4,15,6,27,8,19,27])
index=arr3.argmax()
arr3[index]=0
print(arr3)


[ 1  2 13  4 15  6  0  8 19 27]


given 1d array , negate all elements(-3,-4,-5,-6,-7)
which are between 3 and 8 
for the following array arr4=np.arange(1,11,1)

In [ ]:
arr4=np.arange(1,11,1)
for i in range(len(arr4)):
  if i>=3 and i<=8:
    arr4[i]=arr4[i]*(-1)

print(arr4)




[ 1  2  3 -4 -5 -6 -7 -8 -9 10]


In [ ]:
np_array=np.arange(1,11,1)
index=np.where((np_array>=3) & (np_array<=8))
np_array[index]=np_array[index]*-1
print(np_array)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
arr=np.arange(1,11,1)
for i in range(2,8):
  arr[i]=arr[i]*-1
print(arr)


[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
np_array1=np.arange(1,11,1)
index=np.where((np_array1>=3) & (np_array1<=8))
for i in index:
  np_array1[index]=np.negative(np_array1[index])  #used function negative 
print(np_array1)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
arr4=np.arange(1,11,1)
for i in range(len(arr4)):
  if arr4[i]>=3 and arr4[i]<=8:
    arr4[i]=arr4[i]*(-1)

print(arr4)




[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
import numpy as np

arr = np.arange(11)

arr[3:9] = np.multiply(arr[3:9],-1)

print(arr)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
arr=np.arange(1,11)
for i in range (2,8):
    arr[i]=-arr[i]

print(arr)


[ 1  2 -3 -4 -5 -6 -7 -8  9 10]


In [ ]:
a=np.arange(1,11)
for i in range(2,8):
  a[i]=-(a[i])
  print(a[i],end=' ')


-3 -4 -5 -6 -7 -8 

In [ ]:
num_list = [21,13,19,3,11,5,18] num_list.sort() num_list[len(num_list) // 2] 


SyntaxError: ignored

https://www.practicaldatascience.org/html/exercises/Exercise_numpy.html

Exercise 1
First, lets make a common array to work with.

In [ ]:
import numpy as np
n=np.random.randint(1,10)
print(n)

2


In [ ]:
import numpy as np

n=np.random.randint(1,10)
print(n)

In [ ]:
import numpy as np
for i in range(5):
  n=np.random.randint(1,10)
  print(n)

3
7
8
5
6


**Seed function** is used to save the state of a random function, so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines (for a specific seed value)
random.randint-generates random number but with each execution it gives different number

In [ ]:
import numpy as np

for i in range(5):
  np.random.seed(0)
  n=np.random.randint(1,10)
  print(n)

6
6
6
6
6


In [ ]:
import numpy as np
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

Exercise 2

What is the average value of the second column (to two decimal places)



In [ ]:
import numpy as np
for i in range(5):
  np.random.seed(0)
  n=np.random.randint(1,10,size=(4,3))
  averegrage=np.average(n,axis=0)[0]
  print(n,averegrage)

[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]] 6.0
[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]] 6.0
[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]] 6.0
[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]] 6.0
[[6 1 4]
 [4 8 4]
 [6 3 5]
 [8 7 9]] 6.0


axis=1 means row-wise or column-wise.

In [ ]:

np.average(random_integers,axis=0)[1]

214895.8

In [ ]:
#np.set_printoptions(precision = 2)
a=np.average(random_integers,axis=0)[1]
a = np.around(a, 3)
a


214895.8

In [ ]:
#np.set_printoptions(precision = 2)
a=np.average(random_integers,axis=0)
a

array([204660.05, 214895.8 , 254579.25, 258840.95, 243333.05])

In [ ]:
a = np.random.random((3,3))
print(a)
a = np.around(a, 1)
print(a)

[[0.83 0.78 0.87]
 [0.98 0.8  0.46]
 [0.78 0.12 0.64]]
[[0.8 0.8 0.9]
 [1.  0.8 0.5]
 [0.8 0.1 0.6]]


In [ ]:
a = np.random.random((3,3))
print(a)

[[0.62 0.61 0.62]
 [0.94 0.68 0.36]
 [0.44 0.7  0.06]]


In [ ]:
np.set_printoptions(precision = 1)
print(a)

[[0.6 0.6 0.6]
 [0.9 0.7 0.4]
 [0.4 0.7 0.1]]


In [ ]:
sum1=np.average(random_integers[:,1])
sum1

214895.8

Exercise 3

What is the average value of the first 5 rows of the third and fourth columns?

In [ ]:
s=np.average(random_integers[5:])
s

242646.16

In [ ]:
s1=random_integers[:5,3]
print(s1)
print(np.average(s1))


[140037 481981 394863 485118 109413]
322282.4


Exercise 4
Example for braodcasting

In [ ]:
import numpy as np
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(first_matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
second_matrix = np.array([1, 2, 3])
print(second_matrix)

[1 2 3]


In [ ]:
print(first_matrix + second_matrix)

[[2 4 6]
 [5 7 9]]


Execise 5¶
Keep Python Closed! Write down the final result of the following code:
boolean indexing

In [ ]:
my_vector = np.array([1, 2, 3, 4, 5, 6])
selection = my_vector % 2 == 0
print(selection)
my_vector[selection]

[False  True False  True False  True]


array([2, 4, 6])