<a href="https://colab.research.google.com/github/masnaashraf/Python-and-ML/blob/main/SimpleImputer_IterativeImputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
from sklearn.ensemble import RandomForestRegressor
rfr= RandomForestRegressor(random_state=42)

from sklearn.linear_model import LogisticRegression
log= LogisticRegression()
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier(random_state=42)

# simple imputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

#KNN Imputer
from sklearn.impute import KNNImputer

import warnings
warnings.filterwarnings("ignore")


In [ ]:
data={"SibSp":[1,1,0,1,0,0],"Fare":[7.2500,71.2833,7.2950,53.1000,8.0500,8.4583],"Age":[22,38,26,35,35,np.NaN]}
data

X=pd.DataFrame(data)
X

SibSp     Fare   Age
0      1   7.2500  22.0
1      1  71.2833  38.0
2      0   7.2950  26.0
3      1  53.1000  35.0
4      0   8.0500  35.0
5      0   8.4583   NaN

In [ ]:
#Applying random forest regressor
impute=IterativeImputer(rfr)
impute.fit_transform(X)

array([[ 1.    ,  7.25  , 22.    ],
       [ 1.    , 71.2833, 38.    ],
       [ 0.    ,  7.295 , 26.    ],
       [ 1.    , 53.1   , 35.    ],
       [ 0.    ,  8.05  , 35.    ],
       [ 0.    ,  8.4583, 31.71  ]])

In [ ]:
#reading text data 
horse_colic=pd.read_table("/content/horse-colic.txt",delimiter=',',header=None)

horse_colic.head()

0   1        2      3    4   5  6  7  8  9   ...     18    19 20    21 22  \
0  2   1   530101  38.50   66  28  3  3  ?  2  ...  45.00  8.40  ?     ?  2   
1  1   1   534817   39.2   88  20  ?  ?  4  1  ...     50    85  2     2  3   
2  2   1   530334  38.30   40  24  1  1  3  1  ...  33.00  6.70  ?     ?  1   
3  1   9  5290409  39.10  164  84  4  1  6  2  ...  48.00  7.20  3  5.30  2   
4  2   1   530255  37.30  104  35  ?  ?  6  2  ...  74.00  7.40  ?     ?  2   

  23     24 25 26 27  
0  2  11300  0  0  2  
1  2   2208  0  0  2  
2  2      0  0  0  1  
3  1   2208  0  0  1  
4  2   4300  0  0  2  

[5 rows x 28 columns]

In [ ]:
horse_colic=pd.read_table("/content/horse-colic.txt",delimiter=',',header=None,na_values="?")

horse_colic=pd.DataFrame(horse_colic)
horse_colic.head()

0   1        2     3      4     5    6    7    8    9   ...    18    19  \
0  2.0   1   530101  38.5   66.0  28.0  3.0  3.0  NaN  2.0  ...  45.0   8.4   
1  1.0   1   534817  39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...  50.0  85.0   
2  2.0   1   530334  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  33.0   6.7   
3  1.0   9  5290409  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  48.0   7.2   
4  2.0   1   530255  37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...  74.0   7.4   

    20   21   22  23     24  25  26  27  
0  NaN  NaN  2.0   2  11300   0   0   2  
1  2.0  2.0  3.0   2   2208   0   0   2  
2  NaN  NaN  1.0   2      0   0   0   1  
3  3.0  5.3  2.0   1   2208   0   0   1  
4  NaN  NaN  2.0   2   4300   0   0   2  

[5 rows x 28 columns]

In [ ]:
impute=IterativeImputer(rfr)
horse_colic1=pd.DataFrame(impute.fit_transform(horse_colic),columns=horse_colic.columns)
horse_colic1.head()



0    1          2     3      4     5     6     7     8    9   ...    18  \
0  2.0  1.0   530101.0  38.5   66.0  28.0  3.00  3.00  3.06  2.0  ...  45.0   
1  1.0  1.0   534817.0  39.2   88.0  20.0  2.74  2.86  4.00  1.0  ...  50.0   
2  2.0  1.0   530334.0  38.3   40.0  24.0  1.00  1.00  3.00  1.0  ...  33.0   
3  1.0  9.0  5290409.0  39.1  164.0  84.0  4.00  1.00  6.00  2.0  ...  48.0   
4  2.0  1.0   530255.0  37.3  104.0  35.0  2.65  2.95  6.00  2.0  ...  74.0   

     19    20     21   22   23       24   25   26   27  
0   8.4  2.21  3.727  2.0  2.0  11300.0  0.0  0.0  2.0  
1  85.0  2.00  2.000  3.0  2.0   2208.0  0.0  0.0  2.0  
2   6.7  1.49  4.824  1.0  2.0      0.0  0.0  0.0  1.0  
3   7.2  3.00  5.300  2.0  1.0   2208.0  0.0  0.0  1.0  
4   7.4  2.39  3.586  2.0  2.0   4300.0  0.0  0.0  2.0  

[5 rows x 28 columns]

In [ ]:
car_data= pd.read_csv("/content/Car_sales.csv")

car_data.head()

Manufacturer              Model  Sales in thousands  x_4_year  \
0  Acura          Integra                        16.919    16.360   
1  Acura          TL                             39.384    19.875   
2  Acura          CL                             14.114    18.225   
3  Acura          RL                              8.588    29.725   
4  Audi           A4                             20.397    22.255   

  Vehicle type  Price in thousands  Engine size  Horsepower  Wheelbase  Width  \
0    Passenger               21.50          1.8       140.0      101.2   67.3   
1    Passenger               28.40          3.2       225.0      108.1   70.3   
2    Passenger                 NaN          3.2       225.0      106.9   70.6   
3    Passenger               42.00          3.5       210.0      114.6   71.4   
4    Passenger               23.99          1.8       150.0      102.6   68.2   

   Length  Curb weight  Fuel capacity  Fuel efficiency Latest Launch  \
0   172.4        2.639           13.2             28.0      2-Feb-14   
1   192.9        3.517           17.2             25.0      6-Mar-15   
2   192.0        3.470           17.2             26.0      1-Apr-14   
3   196.6        3.850           18.0             22.0      3-Oct-15   
4   178.0        2.998           16.4             27.0     10-Aug-15   

   Unnamed: 15      XX  
0          NaN  16.360  
1          NaN  19.875  
2          NaN  18.225  
3          NaN  29.725  
4          NaN  22.255

In [ ]:
car_data.isna().sum()

Manufacturer            3
Model                   0
Sales in thousands      0
x_4_year               36
Vehicle type            0
Price in thousands      2
Engine size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb weight             2
Fuel capacity           1
Fuel efficiency         3
Latest Launch           0
Unnamed: 15           157
XX                     36
dtype: int64

In [ ]:
car_data["Manufacturer"]=car_data['Manufacturer'].fillna("BMW")


In [ ]:
car_data.isna().sum()

Manufacturer            0
Model                   0
Sales in thousands      0
x_4_year               36
Vehicle type            0
Price in thousands      2
Engine size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb weight             2
Fuel capacity           1
Fuel efficiency         3
Latest Launch           0
Unnamed: 15           157
XX                     36
dtype: int64

In [ ]:
#selecting only columns with nan values
df=car_data.iloc[:,3:]
df=df.drop(columns=["Vehicle type","Latest Launch","Unnamed: 15"],axis=1)
df.head()

x_4_year  Price in thousands  Engine size  Horsepower  Wheelbase  Width  \
0    16.360               21.50          1.8       140.0      101.2   67.3   
1    19.875               28.40          3.2       225.0      108.1   70.3   
2    18.225                 NaN          3.2       225.0      106.9   70.6   
3    29.725               42.00          3.5       210.0      114.6   71.4   
4    22.255               23.99          1.8       150.0      102.6   68.2   

   Length  Curb weight  Fuel capacity  Fuel efficiency      XX  
0   172.4        2.639           13.2             28.0  16.360  
1   192.9        3.517           17.2             25.0  19.875  
2   192.0        3.470           17.2             26.0  18.225  
3   196.6        3.850           18.0             22.0  29.725  
4   178.0        2.998           16.4             27.0  22.255

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   x_4_year            121 non-null    float64
 1   Price in thousands  155 non-null    float64
 2   Engine size         156 non-null    float64
 3   Horsepower          156 non-null    float64
 4   Wheelbase           156 non-null    float64
 5   Width               156 non-null    float64
 6   Length              156 non-null    float64
 7   Curb weight         155 non-null    float64
 8   Fuel capacity       156 non-null    float64
 9   Fuel efficiency     154 non-null    float64
 10  XX                  121 non-null    float64
dtypes: float64(11)
memory usage: 13.6 KB


In [ ]:
df.head()

x_4_year  Price in thousands  Engine size  Horsepower  Wheelbase  Width  \
0    16.360               21.50          1.8       140.0      101.2   67.3   
1    19.875               28.40          3.2       225.0      108.1   70.3   
2    18.225                 NaN          3.2       225.0      106.9   70.6   
3    29.725               42.00          3.5       210.0      114.6   71.4   
4    22.255               23.99          1.8       150.0      102.6   68.2   

   Length  Curb weight  Fuel capacity  Fuel efficiency      XX  
0   172.4        2.639           13.2             28.0  16.360  
1   192.9        3.517           17.2             25.0  19.875  
2   192.0        3.470           17.2             26.0  18.225  
3   196.6        3.850           18.0             22.0  29.725  
4   178.0        2.998           16.4             27.0  22.255

In [ ]:
impute=IterativeImputer(rfr)
impute = IterativeImputer(rfr)
df_new=pd.DataFrame(impute.fit_transform(df),columns=['x_4_year','Price in thousands', 'Engine size', 'Horsepower',
       'Wheelbase', 'Width', 'Length', 'Curb weight', 'Fuel capacity',
       'Fuel efficiency','XX'])
df_new.head()

x_4_year  Price in thousands  Engine size  Horsepower  Wheelbase  Width  \
0    16.360            21.50000          1.8       140.0      101.2   67.3   
1    19.875            28.40000          3.2       225.0      108.1   70.3   
2    18.225            27.81873          3.2       225.0      106.9   70.6   
3    29.725            42.00000          3.5       210.0      114.6   71.4   
4    22.255            23.99000          1.8       150.0      102.6   68.2   

   Length  Curb weight  Fuel capacity  Fuel efficiency      XX  
0   172.4        2.639           13.2             28.0  16.360  
1   192.9        3.517           17.2             25.0  19.875  
2   192.0        3.470           17.2             26.0  18.225  
3   196.6        3.850           18.0             22.0  29.725  
4   178.0        2.998           16.4             27.0  22.255

In [ ]:
impute=IterativeImputer(rfr)
impute = IterativeImputer(rfr)
df_new=pd.DataFrame(impute.fit_transform(df),columns=df.columns)
df_new.head()

In [ ]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   x_4_year            157 non-null    float64
 1   Price in thousands  157 non-null    float64
 2   Engine size         157 non-null    float64
 3   Horsepower          157 non-null    float64
 4   Wheelbase           157 non-null    float64
 5   Width               157 non-null    float64
 6   Length              157 non-null    float64
 7   Curb weight         157 non-null    float64
 8   Fuel capacity       157 non-null    float64
 9   Fuel efficiency     157 non-null    float64
 10  XX                  157 non-null    float64
dtypes: float64(11)
memory usage: 13.6 KB


Credit RIsk train data- 
dependend variable is Loan status

In [ ]:
crt=pd.read_csv("/content/Credit_Risk_Train_data.csv")
crt.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [ ]:
crt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [ ]:
crt.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
categ=crt.select_dtypes("object")
numeric=crt.select_dtypes("number")

In [ ]:
categ.isna().sum()

Gender           13
Married           3
Dependents       15
Education         0
Self_Employed    32
Property_Area     0
Loan_Status       0
dtype: int64

In [ ]:
categ=categ.drop("Loan_ID",axis=1)

In [ ]:
numeric.isna().sum()

ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
dtype: int64

In [ ]:
numeric.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             1.0

In [ ]:
impute=IterativeImputer(rfr)
impute = IterativeImputer(rfr)
df_new=pd.DataFrame(impute.fit_transform(numeric),columns=numeric.columns)
df_new.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0           5849.0                0.0      140.47             360.0   
1           4583.0             1508.0      128.00             360.0   
2           3000.0                0.0       66.00             360.0   
3           2583.0             2358.0      120.00             360.0   
4           6000.0                0.0      141.00             360.0   

   Credit_History  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             1.0

In [ ]:
df_new.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0           5849.0                0.0      140.47             360.0   
1           4583.0             1508.0      128.00             360.0   
2           3000.0                0.0       66.00             360.0   
3           2583.0             2358.0      120.00             360.0   
4           6000.0                0.0      141.00             360.0   

   Credit_History  
0             1.0  
1             1.0  
2             1.0  
3             1.0  
4             1.0

In [ ]:
categ.head()

Gender Married Dependents     Education Self_Employed Property_Area  \
0   Male      No          0      Graduate            No         Urban   
1   Male     Yes          1      Graduate            No         Rural   
2   Male     Yes          0      Graduate           Yes         Urban   
3   Male     Yes          0  Not Graduate            No         Urban   
4   Male      No          0      Graduate            No         Urban   

  Loan_Status  
0           Y  
1           N  
2           Y  
3           Y  
4           Y

In [ ]:
categ.isna().sum()

Gender           13
Married           3
Dependents       15
Education         0
Self_Employed    32
Property_Area     0
Loan_Status       0
dtype: int64

In [ ]:
knn=KNNImputer()
df_new=pd.DataFrame(knn.fit_transform(categ),columns=categ.columns)
df_new.head()

#categorical variable donot work with knn imputer

ValueError: ignored

In [ ]:
from sklearn.impute import SimpleImputer
simp_imp=SimpleImputer(strategy="most_frequent")


In [ ]:

df_categ=pd.DataFrame(simp_imp.fit_transform(categ),columns=categ.columns)
df_categ.head()


Gender Married Dependents     Education Self_Employed Property_Area  \
0   Male      No          0      Graduate            No         Urban   
1   Male     Yes          1      Graduate            No         Rural   
2   Male     Yes          0      Graduate           Yes         Urban   
3   Male     Yes          0  Not Graduate            No         Urban   
4   Male      No          0      Graduate            No         Urban   

  Loan_Status  
0           Y  
1           N  
2           Y  
3           Y  
4           Y

In [ ]:
df_categ.isna().sum()

Gender           0
Married          0
Dependents       0
Education        0
Self_Employed    0
Property_Area    0
Loan_Status      0
dtype: int64

In [ ]:
car_data1=[df_new,df_categ]

In [ ]:
print(car_data1)

[     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849.0                0.0      140.47             360.0   
1             4583.0             1508.0      128.00             360.0   
2             3000.0                0.0       66.00             360.0   
3             2583.0             2358.0      120.00             360.0   
4             6000.0                0.0      141.00             360.0   
..               ...                ...         ...               ...   
609           2900.0                0.0       71.00             360.0   
610           4106.0                0.0       40.00             180.0   
611           8072.0              240.0      253.00             360.0   
612           7583.0                0.0      187.00             360.0   
613           4583.0                0.0      133.00             360.0   

     Credit_History  
0               1.0  
1               1.0  
2               1.0  
3               1.0  
4           

In [ ]:
car_data_com=pd.concat(car_data1,axis=1,join="inner")
car_data_com.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0           5849.0                0.0      140.47             360.0   
1           4583.0             1508.0      128.00             360.0   
2           3000.0                0.0       66.00             360.0   
3           2583.0             2358.0      120.00             360.0   
4           6000.0                0.0      141.00             360.0   

   Credit_History Gender Married Dependents     Education Self_Employed  \
0             1.0   Male      No          0      Graduate            No   
1             1.0   Male     Yes          1      Graduate            No   
2             1.0   Male     Yes          0      Graduate           Yes   
3             1.0   Male     Yes          0  Not Graduate            No   
4             1.0   Male      No          0      Graduate            No   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [ ]:
car_data_com.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ApplicantIncome    614 non-null    float64
 1   CoapplicantIncome  614 non-null    float64
 2   LoanAmount         614 non-null    float64
 3   Loan_Amount_Term   614 non-null    float64
 4   Credit_History     614 non-null    float64
 5   Gender             614 non-null    object 
 6   Married            614 non-null    object 
 7   Dependents         614 non-null    object 
 8   Education          614 non-null    object 
 9   Self_Employed      614 non-null    object 
 10  Property_Area      614 non-null    object 
 11  Loan_Status        614 non-null    object 
dtypes: float64(5), object(7)
memory usage: 57.7+ KB


In [ ]:
car_data_com["Loan_Status"].unique()

array(['Y', 'N'], dtype=object)

In [ ]:
x = car_data_com.iloc[:,:-1].values
y = car_data_com.iloc[:,-1].values


In [ ]:
print(x)

[[5849.0 0.0 140.47 ... 'Graduate' 'No' 'Urban']
 [4583.0 1508.0 128.0 ... 'Graduate' 'No' 'Rural']
 [3000.0 0.0 66.0 ... 'Graduate' 'Yes' 'Urban']
 ...
 [8072.0 240.0 253.0 ... 'Graduate' 'No' 'Urban']
 [7583.0 0.0 187.0 ... 'Graduate' 'No' 'Urban']
 [4583.0 0.0 133.0 ... 'Graduate' 'Yes' 'Semiurban']]


In [ ]:
x.shape

(614, 11)

In [ ]:
y.shape

(614,)

In [ ]:
x=pd.DataFrame(x)


In [ ]:
#encoding categorical data

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[5,6,7,8,9,10])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[0.0 1.0 1.0 ... 140.47 360.0 1.0]
 [0.0 1.0 0.0 ... 128.0 360.0 1.0]
 [0.0 1.0 0.0 ... 66.0 360.0 1.0]
 ...
 [0.0 1.0 0.0 ... 253.0 360.0 1.0]
 [0.0 1.0 0.0 ... 187.0 360.0 1.0]
 [1.0 0.0 1.0 ... 133.0 360.0 0.0]]


In [ ]:
y=pd.DataFrame(y)

In [ ]:
y.head()

0
0  Y
1  N
2  Y
3  Y
4  Y

In [ ]:
from sklearn.preprocessing import LabelEncoder
dep=LabelEncoder()
y=dep.fit_transform(y)


In [ ]:
print(y)

[1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0
 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0
 1 0 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1
 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1
 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 0 1 0 1
 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0
 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 1 0 1 1
 1 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1
 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 1 1 0 1 0 1 1 1 0 0 1 0 1 1 1 1 0 0 0 1 0
 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 0 1 1 0 1 1
 1 0 0 0 1 0 1 0 1 0 0 1 1 1 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1
 1 1 1 0 0 0 0 1 0 1 1 1 1 0 1 0 1 1 1 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 1
 1 1 1 1 1 0 0 1 0 1 1 1 

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state=2)

In [ ]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
x_train = st.fit_transform(x_train)
x_test = st.fit_transform(x_test)

In [ ]:
#fit the model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 2)
classifier.fit(x_train,y_train)


LogisticRegression(random_state=2)

In [ ]:
y_pred_train = classifier.predict(x_train)

In [ ]:
y_pred_train

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,

In [ ]:
classifier.score(x_train,y_train)

0.8158508158508159

In [ ]:
classifier.score(x_test,y_test)

0.7837837837837838

In [ ]:
y_pred_test = classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_test)

In [ ]:
print(cm)

[[ 24  34]
 [  6 121]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.80      0.41      0.55        58
           1       0.78      0.95      0.86       127

    accuracy                           0.78       185
   macro avg       0.79      0.68      0.70       185
weighted avg       0.79      0.78      0.76       185



In [ ]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(classifier,x,y,cv=5)
scores

array([0.80487805, 0.77235772, 0.78861789, 0.84552846, 0.80327869])

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rdf = RandomForestClassifier(n_estimators=100,random_state =0)

In [ ]:
rdf.fit(x_train,y_train)

RandomForestClassifier(random_state=0)

In [ ]:
y_train_pred = rdf.predict(x_train)
y_test_pred = rdf.predict(x_test)

In [ ]:
rdf.score(x_test,y_test)

0.7675675675675676